---
drivers:
- name: json-file
  enabled: true
  options:
    max-size: 100m
    max-file: "2"

- name: kafka
  enabled: true
  options:
     formatted-logkey: 'clusterQQ:{{labels "io.kubernetes.pod.namespace"}}:{{labels "io.kubernetes.pod.name"}}:{{labels "io.kubernetes.container.name"}}'
#     desired-containers: nginx
     topic: raw_log
     brokers: 10.58.34.101:9092
     #     NoResponse:0    WaitForLocal:1  WaitForAll:-1
     required-ack: '1'
     #    CompressionNone:0    	CompressionGZIP:1 	CompressionSnappy:2    CompressionLZ4:3
     compression: '2'
     #Milliseconds
     flush/frequency: '200'
     flush/bytes: '10000000'
     producer/retry: '3'
     max-message-bytes: '1000000'
     logger-channel-size: '10000'
     circuit-breaker-consec-count: '5'
     #Microseconds
     circuit-breaker-timeout: '100'

- name: fifo
  enabled: false
  options:
    buffer-size: 1m
    kafka/dir: /var/log/docker/fifo/kafka
    kafka/logkey: '{{labels "io.kubernetes.pod.name"}}.{{source}}'
    kafka/filter: '{{labels "io.kubernetes.container.name" | eq "nginx"}}'
    kafka/meta: '{{bash "cat /etc/cluster-name"}}:{{labels "io.kubernetes.pod.namespace"}}:{{labels "io.kubernetes.pod.name"}}:{{labels "io.kubernetes.container.name"}}:false'
    kafka/mixstd: 'false'
    redis/dir: /var/log/docker/fifo/redis
    redis/logkey: '{{labels "io.kubernetes.pod.name"}}'
    redis/filter: 'true'
    redis/meta: '{{inet "eth0,ens192"}}:{{bash "cat /etc/cluster-name"}}:{{labels "io.kubernetes.pod.namespace"}}:{{labels "io.kubernetes.pod.name"}}:{{labels "io.kubernetes.container.name"}}:true'
    redis/mixstd: 'true'
circuit:
    #Microseconds
    timeout: 100
    consec-count: 5